groups:
  - name: database_alerts
    interval: 30s
    rules:
      - alert: HighConnectionCount
        expr: postgresql_connections_active > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connection count"
          description: "{{ $labels.instance }} has {{ $value }} active connections"

      - alert: SlowQueries
        expr: rate(postgresql_slow_queries_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many slow queries"
          description: "{{ $labels.instance }} has {{ $value }} slow queries per second"

      - alert: LowCacheHitRate
        expr: redis_keyspace_hits_total / (redis_keyspace_hits_total + redis_keyspace_misses_total) < 0.8
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low Redis cache hit rate"
          description: "Cache hit rate is {{ $value | humanize }}%"

      - alert: HighDiskUsage
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.2
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High disk usage"
          description: "{{ $labels.instance }} has only {{ $value | humanize }}% disk space left"
