import { Registry, Counter, Histogram, Gauge } from 'prom-client';
export declare const register: Registry<"text/plain; version=0.0.4; charset=utf-8">;
export declare const rpcRequestsTotal: Counter<"status" | "method" | "endpoint">;
export declare const rpcRequestDuration: Histogram<"method" | "endpoint">;
export declare const rpcFailuresTotal: Counter<"error" | "method" | "endpoint">;
export declare const rpcHealthStatus: Gauge<"endpoint">;
export declare const rpcLatency: Gauge<"endpoint">;
export declare const transactionsSubmitted: Counter<"type">;
export declare const transactionsConfirmed: Counter<"type">;
export declare const transactionsFailed: Counter<"type" | "reason">;
export declare const transactionConfirmationTime: Histogram<"type">;
export declare const mintsInitiated: Counter<string>;
export declare const mintsCompleted: Counter<string>;
export declare const mintsFailed: Counter<"reason">;
export declare const mintDuration: Histogram<string>;
export declare const treasuryBalance: Gauge<string>;
export declare const treasuryBalanceChecks: Counter<string>;
export declare const lowBalanceAlerts: Counter<string>;
export declare const retryAttempts: Counter<"operation" | "attempt">;
export declare const circuitBreakerState: Gauge<"operation">;
export declare const circuitBreakerTrips: Counter<"operation">;
export declare const queueJobsAdded: Counter<"queue">;
export declare const queueJobsCompleted: Counter<"queue">;
export declare const queueJobsFailed: Counter<"reason" | "queue">;
export declare const queueSize: Gauge<"status" | "queue">;
export declare const queueJobDuration: Histogram<"queue">;
export declare const httpRequestsTotal: Counter<"method" | "route" | "status_code">;
export declare const httpRequestDuration: Histogram<"method" | "route">;
export declare const cacheHits: Counter<"cache_type">;
export declare const cacheMisses: Counter<"cache_type">;
export declare const cacheSize: Gauge<"cache_type">;
export declare const serviceUptime: Gauge<string>;
export declare const activeConnections: Gauge<string>;
export declare function recordHttpRequest(method: string, route: string, statusCode: number, durationSeconds: number): void;
export declare function recordRpcRequest(method: string, endpoint: string, status: 'success' | 'failure', durationSeconds: number, error?: string): void;
export declare function trackMintOperation(status: 'initiated' | 'completed' | 'failed', durationSeconds?: number, reason?: string): void;
export default register;
//# sourceMappingURL=metrics.d.ts.map